POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
###
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyOTAzNzAwfQ.kbLzmIDEkbFhbahXtqpJyZ1x_WWJUw2IIiUbaHOObjc
###

GET http://localhost:3000/states/32/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyOTAzNzAwfQ.kbLzmIDEkbFhbahXtqpJyZ1x_WWJUw2IIiUbaHOObjc
###


POST http://localhost:3000/districts/

Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###

GET http://localhost:3000/districts/323/
###

DELETE http://localhost:3000/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg3ODY0MDA5fQ.iyhq52E28NF12FGWy6bPvRMlpe7L3Rh-XkEt6hbVBxw
###

PUT http://localhost:3000/districts/322/

Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

GET http://localhost:3000/states/22/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg3ODY0MDA5fQ.iyhq52E28NF12FGWy6bPvRMlpe7L3Rh-XkEt6hbVBxw
###

GET http://localhost:3000/districts/323/details/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjg3ODY0MDA5fQ.iyhq52E28NF12FGWy6bPvRMlpe7L3Rh-XkEt6hbVBxw